"""empty message

Revision ID: 8abe34f0914c
Revises: 
Create Date: 2023-06-24 16:13:08.509375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abe34f0914c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONTASBANCARIAS',
    sa.Column('idcontasbancarias', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banco', sa.Integer(), nullable=True),
    sa.Column('agencia', sa.Integer(), nullable=True),
    sa.Column('contabancaria', sa.Integer(), nullable=True),
    sa.Column('codigoauxiliar', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idcontasbancarias')
    )
    op.create_table('clientes',
    sa.Column('Idcliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Razao_social', sa.String(length=255), nullable=True),
    sa.Column('Nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('Cnpj', sa.String(length=255), nullable=False),
    sa.Column('Inscricao_estadual', sa.String(length=255), nullable=True),
    sa.Column('Telefone', sa.String(length=255), nullable=True),
    sa.Column('Celular', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Danfe', sa.String(length=255), nullable=True),
    sa.Column('Site', sa.String(length=255), nullable=True),
    sa.Column('Vendedor', sa.String(length=255), nullable=True),
    sa.Column('Visita', sa.String(length=255), nullable=True),
    sa.Column('Observacoes', sa.String(length=255), nullable=True),
    sa.Column('Caixa_postal', sa.String(length=255), nullable=True),
    sa.Column('Status', sa.String(length=255), nullable=True),
    sa.Column('Pagamentos', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Idcliente'),
    sa.UniqueConstraint('Cnpj')
    )
    op.create_table('numerosorcamentos',
    sa.Column('idnumeroorcamentos', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idcliente', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.String(length=255), nullable=True),
    sa.Column('idrepresentada', sa.Integer(), nullable=True),
    sa.Column('representada', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idnumeroorcamentos')
    )
    op.create_table('representadas',
    sa.Column('Idrepresentada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Razaosocial', sa.String(length=255), nullable=True),
    sa.Column('Cnpj', sa.String(length=255), nullable=True),
    sa.Column('Inscricaoestadual', sa.String(length=255), nullable=True),
    sa.Column('Telefone', sa.String(length=255), nullable=True),
    sa.Column('Endereco', sa.String(length=255), nullable=True),
    sa.Column('Bairro', sa.String(length=255), nullable=True),
    sa.Column('Cidade', sa.String(length=255), nullable=True),
    sa.Column('Estado', sa.String(length=255), nullable=True),
    sa.Column('Cep', sa.String(length=255), nullable=True),
    sa.Column('Comissao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Idrepresentada')
    )
    op.create_table('transportadoras',
    sa.Column('idtransportadora', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transportadora', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idtransportadora')
    )
    op.create_table('usuarios',
    sa.Column('idusuarios', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idusuarios'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendedores',
    sa.Column('idvendedor', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('celular', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=255), nullable=True),
    sa.Column('areaatuacao', sa.String(length=255), nullable=True),
    sa.Column('comissao', sa.Integer(), nullable=True),
    sa.Column('banco', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idvendedor')
    )
    op.create_table('visita',
    sa.Column('idvisita', sa.Integer(), nullable=False),
    sa.Column('idcliente', sa.Integer(), nullable=True),
    sa.Column('razaosocial', sa.String(length=255), nullable=True),
    sa.Column('idcontato', sa.Integer(), nullable=True),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.Column('datadavisita', sa.DateTime(), nullable=True),
    sa.Column('motivovisita', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idvisita')
    )
    op.create_table('clientescontatos',
    sa.Column('Idclientecontato', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.Column('Cargo', sa.String(length=255), nullable=True),
    sa.Column('Telefone', sa.String(length=255), nullable=True),
    sa.Column('Ramal', sa.String(length=255), nullable=True),
    sa.Column('Celular', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('idcliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcliente'], ['clientes.Idcliente'], ),
    sa.PrimaryKeyConstraint('Idclientecontato')
    )
    op.create_table('clientesenderecos',
    sa.Column('Idclientesenderecos', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finalidade', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=255), nullable=True),
    sa.Column('idcliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcliente'], ['clientes.Idcliente'], ),
    sa.PrimaryKeyConstraint('Idclientesenderecos')
    )
    op.create_table('contatos_realizados',
    sa.Column('Id_contato_realizados', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Data_contato', sa.String(length=255), nullable=True),
    sa.Column('Pessoa_de_contato', sa.String(length=255), nullable=True),
    sa.Column('Metodo_de_contato', sa.String(length=255), nullable=True),
    sa.Column('Descricao', sa.String(length=255), nullable=True),
    sa.Column('idcliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcliente'], ['clientes.Idcliente'], ),
    sa.PrimaryKeyConstraint('Id_contato_realizados')
    )
    op.create_table('representadascontatos',
    sa.Column('Idcontatorepresentada', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(length=255), nullable=True),
    sa.Column('Cargo', sa.String(length=255), nullable=True),
    sa.Column('Telefone', sa.String(length=255), nullable=True),
    sa.Column('Celular', sa.String(length=255), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.Column('Idrepresentada', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Idrepresentada'], ['representadas.Idrepresentada'], ),
    sa.PrimaryKeyConstraint('Idcontatorepresentada')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representadascontatos')
    op.drop_table('contatos_realizados')
    op.drop_table('clientesenderecos')
    op.drop_table('clientescontatos')
    op.drop_table('visita')
    op.drop_table('vendedores')
    op.drop_table('usuarios')
    op.drop_table('transportadoras')
    op.drop_table('representadas')
    op.drop_table('numerosorcamentos')
    op.drop_table('clientes')
    op.drop_table('CONTASBANCARIAS')
    # ### end Alembic commands ###
